// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6lAt0UMv8csub3q2mbakA5RdtPtOzb3o',
    appId: '1:555007478046:web:f369315ba283d86400e10f',
    messagingSenderId: '555007478046',
    projectId: 'data-61e35',
    authDomain: 'data-61e35.firebaseapp.com',
    storageBucket: 'data-61e35.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoihs3JjzkVHEKSYy-x9vKwBhG5VtDYQ8',
    appId: '1:555007478046:android:a638642bf133ee2700e10f',
    messagingSenderId: '555007478046',
    projectId: 'data-61e35',
    storageBucket: 'data-61e35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1bTodSvwrYEBYsIsMVIW3MEfiz7zKl1M',
    appId: '1:555007478046:ios:33bb08fc0311e8ca00e10f',
    messagingSenderId: '555007478046',
    projectId: 'data-61e35',
    storageBucket: 'data-61e35.appspot.com',
    iosBundleId: 'com.example.wearStoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1bTodSvwrYEBYsIsMVIW3MEfiz7zKl1M',
    appId: '1:555007478046:ios:3df68bb001abdb8c00e10f',
    messagingSenderId: '555007478046',
    projectId: 'data-61e35',
    storageBucket: 'data-61e35.appspot.com',
    iosBundleId: 'com.example.wearStoreApp.RunnerTests',
  );
}
